<?php require 'header.phtml'  ?>

    <div class="d-flex justify-content-end mb-3 ">
            <button class="btn btn-success" href="">agregar Producto <i class="fa-solid fa-plus" style="color: #000000;"></i></button>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre del Producto</th>
                <th>Precio</th>
                <th>Acciones</th>
            </tr>
        </thead>
        <tbody>
            <?php
            
            ?>
        </tbody>
    </table>

 

<?php require 'footer.phtml' ?>