
<div class="banner">
		<div class="capa"></div>
		<div class="info">
			<h1>Bienvenidos a </h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facere alias nobis debitis provident ut odio aperiam quibusdam. Amet, neque, illo.</p>
			<button class="btn btn-warning" onclick="scrollToSection('Tienda')">ir a la Tienda</button>

		</div>
</div>
<style>
    .banner{
	width: 100%;
	height: 600px;
	animation: banner 10s infinite linear alternate;
	background-size: 100% 100%;
	position: relative;
	display: flex;
	justify-content: center;
	align-items: center;
}
@keyframes banner{
	0%, 20%{
		background-image: url("./images/banner.jpg");
	}
	25%, 45%{
		background-image: url("./images/banner1.jpg");
	}
	50%, 100%{
		background-image: url("./images/banner3.jpg");
	}	
}
.capa{
	width: 100%;
	height: 100%;
	position: absolute;
	top: 0;
	left: 0;
	background: rgba(0,0,0,0.6);
}
.info{
	z-index: 1;
	width: 100%;
	max-width: 550px;
	text-align: center;
}
.info h1{
	color: #fff;
	font-size: 45px;
	margin-bottom: 20px;
	letter-spacing: 1px;
}
</style>
<script> // pongo la funcion de javascript en cada componente ya que por archivo no toma la ruta y no funciona de manera adecuada
	    console.log('hola')
		function scrollToSection(sectionId) {
			
        	let section = document.getElementById('Tienda')
			console.log(section)
        if (section) {
			console.log("hola");
            section.scrollIntoView({ behavior: 'smooth' });
        }
    }
   
   
</script>
