
<footer class="bg-dark text-light text-center  fixed-bottom"">
        <div class="container">
            <p>&copy; 2023 . Todos los derechos reservados.</p>
            <p>Información de contacto: <a href="mailto:info@miempresa.com">info@miempresa.com</a></p>
        </div>
 </footer>
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script> 
</html>