<?php include 'header.phtml'?>
<div class="container">
        <h2 class="p-1">Agregar Producto</h2>
        <form action="add" method="POST">
            <?php if ($error) : ?>
            <div class='alert alert-danger' role='alert'>
                <?= $error ?>
            </div> 
        <?php endif ?>
            <div class="form-group ">
                <label for="nombre">Nombre del Producto:</label>
                <input type="text" class="form-control"  name='tittle'id="nombre" placeholder="Ingrese el nombre del producto">
            </div>
            <div class="form-group">
                <label for="descripcion">Descripción:</label>
                <textarea class="form-control" id="descripcion"  name='description' rows="3" placeholder="Ingrese la descripción del producto"></textarea>
            </div>
            <div class="form-group">
                <label for="stock">Stock:</label>
                <input type="number" class="form-control" id="stock"  name="stock" placeholder="Ingrese la cantidad en stock">
            </div>
            <div class="form-group">
                <label for="precio">Precio:</label>
                <input type="number" class="form-control" id="precio"  name="price" placeholder="Ingrese el precio del producto">
            </div>
            <div class="form-group">
                <label for="marca">Marca:</label>
                <select class="form-control" name='marcaID' id="marca">
                  
                  <?php foreach ($marcas as $marca):?>
                    <?php var_dump($marcas)  ?>
                     <option value="<?= $marca->MarcaID ?>" > <?= $marca->Nombre ?></option>

                    <?php endforeach?>
                </select>
               
            </div>
            <div class="form-group">
                <label for="condicion">Condición:</label>
                <select class="form-control"  name='condition'id="condicion">
                    <option value="Nuevo">Nuevo</option>
                    <option value="Usado">Usado</option>
                </select>
            </div>
           
            <button  type="submit" class="btn btn-primary mt-2">Agregar Producto</button>
        </form>
    </div>
<?php include 'footer.phtml'?>
