<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Ecommerce Celulares Reacondicionados</title>
  <link rel="stylesheet" href="../css/style.css">
  <script src="https://kit.fontawesome.com/5bbc4115cb.js" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

  <base href=<?php echo BASE_URL; ?>>
</head>

<nav class="navbar navbar-expand-lg bg-black navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="home">Ecommerce</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="home">Home</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Productos
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">  
              <?php foreach ($marcas as $marca): ?>
              <li><a class="dropdown-item" href="productosMarca/<?= $marca->MarcaID ?>">    <?=$marca->Nombre ?></a></li>
              <?php endforeach ?>
          </ul>
        </li>
      </ul>
      
    </div>
    
    <ul class="navbar-nav align-items-center ml-4 p-2">
    <?php if (!isset($_SESSION['USER_ID'])) : ?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="login"><i class="fa-solid fa-user fa-xl"></i></a>
          </li>
        <?php else : ?>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="logout">Logout (<?=  $_SESSION['USER_USERNAME']?>)</a>
          </li>
        <?php endif?>
        <li>
        <a class="nav-item"><i class="fa-solid fa-cart-shopping fa-lg" style="color: #df572a;"></i></a>
        </li>
      
      </ul>    
      
  </div>
</nav>
<body>