<?php require './templates/header.phtml' ?>
<div class="wrapper">
<?php require './templates/banner.phtml' ?>
<section id="Tienda  style="min-height: 82vh" class="container text-center mt-2">
    <div class="row">
        <?php if((count($products)>0)):?>
         <?php foreach ($products as $product) : ?>
            <div class="col-md-4 mb-4">
                <div class="card mx-auto" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title"><?= $product->NombreProducto ?></h5>
                        <h6 class="card-subtitle mb-2 text-muted"><?= $product->Nombre?></h6>
                        <p class="card-text"><?= $product->Descripcion ?></p>
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Precio: $<?= $product->Precio ?></li>
                        <li class="list-group-item">Disponibilidad: <?= $product->Stock > 0 ? 'En Stock' : 'Agotado' ?></li>
                    </ul>
                    <div class="card-body">
                        <a href="#" class="btn btn-primary">Agregar al carrito</a>
                    </div>
                </div>
            </div>
         <?php endforeach;?>
         <?php else : ?>
            <div class="alert alert-danger" role="alert">
                <h1>no se encontraron los productos para esta marca</h1>
            </div>
            
        <?php endif ?>
    </div>
</section>
</div>
<?php require './templates/footer.phtml' ?>