<?php require 'header.phtml' ?>




<div class="row product-container">
    <div class="col-md-5 order-md-1">
     <img class="card-img-top"  src="<?= $Item->Imagen ?>" alt="" srcset="">
    </div>

    <div class="col-md-7 order-md-2">
        <h2 class="product-title"><?= $Item->NombreProducto ?></h2>
        <p class="lead product-price"><?= $Item->Precio ?></p>
        <div class="col-3 my-3">
            <input class="form-control" id="cantidad" name="cantidad" type="number" min="1" max="10" value="1">
        </div>
        <div class="product-details">
            <h4>Descripción:</h4>
            <p><?= $Item->Descripcion ?></p>
            <h4>Marca:</h4>
            <p><?= $Item->Nombre ?></p>
            <h4>Condición:</h4>
            <p><?= $Item->Condicion ?></p>
        </div>
        <div class="d-grid gap-3 col-7">
            <button class="btn btn-primary" type="button">Comprar ahora</button>
            <button class="btn btn-outline-primary" type="button">Agregar al carrito</button>
        </div>
    </div>
</div>

<?php require 'footer.phtml'; ?>
