<?php require 'header.phtml' ?>
<?php require_once './App/controllers/helpers/marcasHelper.php' ?>

<div class="d-flex justify-content-end mb-3 ">
            <a class="btn btn-success" href="viewFormAddMarca">Agregar Marca <i class="fa-solid fa-plus" style="color: #000000;"></i></a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre de la marca</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($marcas as $marca): ?>
        <tr>
            <td><?php echo $marca->MarcaID; ?></td>
            <td><?php echo $marca->Nombre; ?></td>
            <td>
            <div class="d-grid gap-2 d-md-flex justify-content-md-end">

                <?php if (MarcasHelper::estaEnUso($marca->MarcaID)): ?>
                        <!-- La marca está en uso, muestra un mensaje y deshabilita la opción de eliminar -->
                        <span class="text-danger">Esta marca está en uso en productos.</span>
                    <?php else: ?>
                        <!-- La marca no está en uso, permite eliminarla -->
                        <a class="btn btn-outline-danger me-md-2 p-2" type="button" href="deleteMarca/<?php echo $marca->MarcaID ?>"><i class="fa-solid fa-trash"></i></a>
                    <?php endif; ?>

                    <button class="btn btn-outline-warning edit-button" type="button" data-bs-toggle="modal" data-bs-target="#modalMarcas"
                     data-product-id="<?= $marca->MarcaID; ?>" 
                     data-product-nombre="<?= $marca->Nombre; ?>" 
                    
                            <i class="fa-solid fa-pen-to-square" style="color: #e0b310;"></i>
                    </button>
            </div> 
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<div>
    <?php require 'modalEditMarca.phtml' ?>
    <?php require 'footer.phtml' ?>
</div>